version: "3"

services:

    php-apache:
        # user: "502:20" #-> MacOS
        # user: "1000:1000" #-> Unix 
        ports: 
            - "8686:80"

    mariadb:
        ports: 
            - "3306:3306"
  
    phpmyadmin:
        ports:
            - "8687:80"
            